spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ASS2;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    #show-sql: true
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 172800000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#frontend-url: http://localhost:5173

# CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dawqytffc
cloudinary:
  cloud-name: dawqytffc
  api-key: 233677167656433
  api-secret: 8kfFxYc6xPzaMM25boKVCESDpaE